CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Ingredients" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_Ingredients" PRIMARY KEY ("Id")
);

CREATE TABLE "Recipes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ExternalId" text NOT NULL,
    "Source" text NOT NULL,
    "Title" text NOT NULL,
    "Category" text NOT NULL,
    "Area" text NOT NULL,
    "Instructions" text NOT NULL,
    "ImageUrl" text NOT NULL,
    "IsDrink" boolean NOT NULL,
    CONSTRAINT "PK_Recipes" PRIMARY KEY ("Id")
);

CREATE TABLE "RecipeIngredients" (
    "RecipeId" integer NOT NULL,
    "IngredientId" integer NOT NULL,
    "Quantity" text NOT NULL,
    CONSTRAINT "PK_RecipeIngredients" PRIMARY KEY ("RecipeId", "IngredientId"),
    CONSTRAINT "FK_RecipeIngredients_Ingredients_IngredientId" FOREIGN KEY ("IngredientId") REFERENCES "Ingredients" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RecipeIngredients_Recipes_RecipeId" FOREIGN KEY ("RecipeId") REFERENCES "Recipes" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_Ingredients_Name" ON "Ingredients" ("Name");

CREATE INDEX "IX_RecipeIngredients_IngredientId" ON "RecipeIngredients" ("IngredientId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250911054137_InitialCreate', '9.0.9');

CREATE TABLE "CockTails" (
    "Id" text NOT NULL,
    "Name" text NOT NULL,
    "Category" text NOT NULL,
    "Alcoholic" text NOT NULL,
    "Glass" text NOT NULL,
    "Instructions" text NOT NULL,
    "Thumbnail" text NOT NULL,
    CONSTRAINT "PK_CockTails" PRIMARY KEY ("Id")
);

CREATE TABLE "DrinkIngredients" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_DrinkIngredients" PRIMARY KEY ("Id")
);

CREATE TABLE "DrinkRecipeIngredients" (
    "CockTailId" text NOT NULL,
    "DrinkIngredientId" integer NOT NULL,
    "Measure" text NOT NULL,
    CONSTRAINT "PK_DrinkRecipeIngredients" PRIMARY KEY ("CockTailId", "DrinkIngredientId"),
    CONSTRAINT "FK_DrinkRecipeIngredients_CockTails_CockTailId" FOREIGN KEY ("CockTailId") REFERENCES "CockTails" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_DrinkRecipeIngredients_DrinkIngredients_DrinkIngredientId" FOREIGN KEY ("DrinkIngredientId") REFERENCES "DrinkIngredients" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_DrinkIngredients_Name" ON "DrinkIngredients" ("Name");

CREATE INDEX "IX_DrinkRecipeIngredients_DrinkIngredientId" ON "DrinkRecipeIngredients" ("DrinkIngredientId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250914223925_AddCocktailTables', '9.0.9');

ALTER TABLE "Recipes" ADD "IsGlutenFree" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Recipes" ADD "IsKeto" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Recipes" ADD "IsPaleo" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Recipes" ADD "IsVegan" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Recipes" ADD "IsVegetarian" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "CockTails" ADD "IsGlutenFree" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "CockTails" ADD "IsKeto" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "CockTails" ADD "IsPaleo" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "CockTails" ADD "IsVegan" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "CockTails" ADD "IsVegetarian" boolean NOT NULL DEFAULT FALSE;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251001043720_AddDietClassifications', '9.0.9');

ALTER TABLE "Recipes" ADD "Calories" integer;

ALTER TABLE "Recipes" ADD "Carbohydrates" real;

ALTER TABLE "Recipes" ADD "Fat" real;

ALTER TABLE "Recipes" ADD "Fiber" real;

ALTER TABLE "Recipes" ADD "NutritionCalculatedAt" timestamp with time zone;

ALTER TABLE "Recipes" ADD "Protein" real;

ALTER TABLE "Recipes" ADD "Sodium" real;

ALTER TABLE "Recipes" ADD "Sugar" real;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251004223141_AddNutritionToRecipes', '9.0.9');

ALTER TABLE "CockTails" ADD "Calories" integer;

ALTER TABLE "CockTails" ADD "Carbohydrates" real;

ALTER TABLE "CockTails" ADD "Fat" real;

ALTER TABLE "CockTails" ADD "Fiber" real;

ALTER TABLE "CockTails" ADD "NutritionCalculatedAt" timestamp with time zone;

ALTER TABLE "CockTails" ADD "Protein" real;

ALTER TABLE "CockTails" ADD "Sodium" real;

ALTER TABLE "CockTails" ADD "Sugar" real;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251009135325_AddCocktailNutritionCache', '9.0.9');

ALTER TABLE "CockTails" ADD "Alcohol" real;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251009223753_AddAlcoholField', '9.0.9');

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251009225243_AddAlcoholToCocktails', '9.0.9');

COMMIT;

