GET http://localhost:5261/

###
POST http://localhost:5261/validate-ingredient
Content-Type: application/json

{
  "Ingredient": "Beef"
}

### Test Database Connection
GET http://localhost:5261/api/test/db
Accept: application/json 
###
 
### Seed MealDB Recipes
POST http://localhost:5261/seed-mealdb
Accept: application/json

###