GET http://localhost:5261/

###
POST http://localhost:5261/validate-ingredient
Content-Type: application/json

{
  "Ingredient": "Beef"
}

### Test Database Connection
GET http://localhost:5261/api/test/db
Accept: application/json 
###
 
### Seed MealDB Recipes
POST http://localhost:5261/seed-mealdb
Accept: application/json
###

### Get All Recipes
POST http://localhost:5261/seed-cocktaildb
Content-Type: application/json


### Test 1: Basic connectivity
GET http://localhost:5261/test-openrouter-reachability

### Test 2: Detailed service test  
GET http://localhost:5261/test-openrouter-detailed

### Test 3: Recipe endpoint
GET http://localhost:5261/recipe/52772

### reclassify-diets
POST http://localhost:5261/reclassify-diets
Content-Type: application/json



